# Generated by Django 4.2.11 on 2024-07-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='no sender', max_length=50),
            preserve_default=False,
        ),
    ]
